namespace ContosoDashboard.Services;

/// <summary>
/// Storage abstraction for uploaded document files. The training build uses the local
/// filesystem; production can swap in an Azure Blob Storage implementation via DI.
/// </summary>
public interface IFileStorageService
{
    // storageKey is a relative key "{userId}/{projectId|personal}/{guid}.{ext}" generated by the caller.
    // Returns the key actually stored (the same value for local storage).
    Task<string> UploadAsync(Stream fileStream, string storageKey, string contentType);
    Task DeleteAsync(string storageKey);
    Task<Stream> DownloadAsync(string storageKey);
    Task<string> GetUrlAsync(string storageKey, TimeSpan expiration);
}

public class LocalFileStorageService : IFileStorageService
{
    private readonly string _rootPath;

    public LocalFileStorageService(IConfiguration configuration, IWebHostEnvironment environment)
    {
        var configuredRoot = configuration["FileStorage:RootPath"] ?? "AppData/uploads";
        _rootPath = Path.GetFullPath(Path.Combine(environment.ContentRootPath, configuredRoot));
    }

    public async Task<string> UploadAsync(Stream fileStream, string storageKey, string contentType)
    {
        var fullPath = ResolvePath(storageKey);
        Directory.CreateDirectory(Path.GetDirectoryName(fullPath)!);

        // CreateNew: never overwrite an existing file (keys are GUID-based and must be unique)
        await using var output = new FileStream(fullPath, FileMode.CreateNew, FileAccess.Write, FileShare.None,
            bufferSize: 81920, useAsync: true);
        await fileStream.CopyToAsync(output);

        return storageKey;
    }

    public Task DeleteAsync(string storageKey)
    {
        var fullPath = ResolvePath(storageKey);
        if (File.Exists(fullPath))
        {
            File.Delete(fullPath);
        }

        return Task.CompletedTask;
    }

    public Task<Stream> DownloadAsync(string storageKey)
    {
        var fullPath = ResolvePath(storageKey);
        if (!File.Exists(fullPath))
        {
            throw new FileNotFoundException("Stored document file not found.", storageKey);
        }

        Stream stream = new FileStream(fullPath, FileMode.Open, FileAccess.Read, FileShare.Read,
            bufferSize: 81920, useAsync: true);
        return Task.FromResult(stream);
    }

    public Task<string> GetUrlAsync(string storageKey, TimeSpan expiration)
    {
        // Reserved for a future Azure implementation (SAS URLs)
        throw new NotSupportedException("Local files are served only through the authorized document endpoints.");
    }

    // Resolves a storage key to a full path and prevents path traversal outside the storage root
    private string ResolvePath(string storageKey)
    {
        var relativePath = storageKey.Replace('/', Path.DirectorySeparatorChar);
        var fullPath = Path.GetFullPath(Path.Combine(_rootPath, relativePath));

        if (!fullPath.StartsWith(_rootPath + Path.DirectorySeparatorChar, StringComparison.Ordinal))
        {
            throw new InvalidOperationException("Invalid storage key.");
        }

        return fullPath;
    }
}
